Added some fixes and new scripts

diff --git a/settings/linux/home/aliases b/settings/linux/home/aliases
--- a/settings/linux/home/aliases
+++ b/settings/linux/home/aliases
@@ -115,3 +115,29 @@ alias prettyjson='python -m json.tool'
 
 alias pssh='psg ssh'
 
+#alias assume-role='function(){eval $(command assume-role $@);}'
+
+
+aws_profiles () {
+    [[ -r "${AWS_CONFIG_FILE:-$HOME/.aws/config}" ]] || return 1
+    grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} '\[profile' "${AWS_CONFIG_FILE:-$HOME/.aws/config}" | sed -e 's/.*profile \([a-zA-Z0-9_\.-]*\).*/\1/'
+}
+
+asp () {
+    if [[ -z "$1" ]]
+    then
+        unset AWS_DEFAULT_PROFILE AWS_PROFILE AWS_EB_PROFILE
+        echo AWS profile cleared.
+        return
+    fi
+    local available_profiles=($(aws_profiles))
+    if [[ -z "${available_profiles[(r)$1]}" ]]
+    then
+        echo "${fg[red]}Profile '$1' not found in '${AWS_CONFIG_FILE:-$HOME/.aws/config}'" >&2
+        echo "Available profiles: ${(j:, :)available_profiles:-no profiles found}${reset_color}" >&2
+        return 1
+    fi
+    export AWS_DEFAULT_PROFILE=$1
+    export AWS_PROFILE=$1
+    export AWS_EB_PROFILE=$1
+}
